---

- name: Run command on Ansible host
  hosts: localhost
  tasks:
    - name: Remove SSH key
      local_action: 
        module: command 
        args: 
          cmd: ssh-keygen -f /home/ubuntu/.ssh/known_hosts -R 44.198.29.234

- hosts: all
  become: true
 
  tasks:
    - name: Install docker using snap
      community.general.snap:
        name: docker
        classic: true

    - name: Clone the repository
      git:
        repo: https://github.com/ash8m/myflix.git
        dest: /home/ubuntu/myflix

    - name: run docker compose
      command: docker compose up -d
      become: yes
      args:
        chdir: /home/ubuntu/myflix/

    - name: Wait for restheart port 8080 to become open
      wait_for:
        port: 8080
        delay: 10
        timeout: 300

    - name: add catalogue to mongo using restheart
      command: ./add-catalogue.sh
      args:
        chdir: /home/ubuntu/myflix/

    - name: Copy media files to remote
      copy:
        src: /home/ubuntu/video-content.tar.gz
        dest: /home/ubuntu/video-content.tar.gz

    - name: Untar the file on remote
      unarchive:
        src: /home/ubuntu/video-content.tar.gz
        dest: /home/ubuntu/myflix/services/nginx-video/
        remote_src: yes
        extra_opts: [--gzip]

...
