---

- name: Run command on Ansible host
  hosts: localhost
  become: true
  tasks:
    - name: Check if known_hosts file exists
      stat:
        path: /home/ubuntu/.ssh/known_hosts
      register: result

    - name: Remove SSH key
      local_action: 
        module: command 
        args: 
          cmd: ssh-keygen -f /home/ubuntu/.ssh/known_hosts -R 44.198.29.234
      when: result.stat.exists

- hosts: all
  become: true

  vars:
    video_urls: 
      - http://23.21.89.111/bbb.mp4
      - http://23.21.89.111/InterviewGNULinux.mp4
      - http://23.21.89.111/CarlSaganMars.mp4

    thumbnail_urls:
      - http://23.21.89.111/pics/bbb.png
      - http://23.21.89.111/pics/bbb-th.png
      - http://23.21.89.111/pics/InterviewGNULinux.png
      - http://23.21.89.111/pics/CarlSaganMars.png   


 
  tasks:
    - name: Install docker using snap
      community.general.snap:
        name: docker
        classic: true

    - name: Clone the repository
      git:
        repo: https://github.com/ash8m/myflix.git
        dest: /home/ubuntu/myflix

    - name: run docker compose
      command: docker compose up -d
      become: yes
      args:
        chdir: /home/ubuntu/myflix/

    - name: Wait for restheart port 8080 to become open
      wait_for:
        port: 8080
        delay: 10
        timeout: 300

    - name: add catalogue to mongo using restheart
      command: ./add-catalogue.sh
      args:
        chdir: /home/ubuntu/myflix/

    - name: Download files using get_url
      get_url:
        url: "{{ item }}"
        dest: /home/ubuntu/myflix/services/nginx-video/mp4
      loop: "{{ video_urls }}"
    
    - name: Download files using get_url
      get_url:
        url: "{{ item }}"
        dest: /home/ubuntu/myflix/services/nginx-video/www/pics
      loop: "{{ thumbnail_urls }}"   

...
