---
- hosts: all
 
  tasks:
    - name: Install docker using snap
      community.general.snap:
        name: docker

    - name: Clone the repository
      git:
        repo: https://github.com/ash8m/myflix.git
        dest: /home/ubuntu

    - name: run docker compose
      command: docker compose up -d
      become: yes
      args:
        chdir: /home/ubuntu/myflix/

    - name: Wait for restheart port 8080 to become open
      wait_for:
        port: 8080
        delay: 10
        timeout: 300

    - name: Run a command at a specific path
      command: add-catalogue.sh
      args:
        chdir: /home/ubuntu/myflix/

    - name: Copy media files to remote
      copy:
        src: /home/ubuntu/video-content.tar.gz
        dest: /home/ubuntu/video-content.tar.gz

    - name: Untar the file on remote
      unarchive:
        src: /home/ubuntu/video-content.tar.gz
        dest: /home/ubuntu/myflix/services/nginx-video/
        remote_src: yes
        extra_opts: [--gzip]

...


 