version: "3"

services:
  tfrecomm:
    image: ash8m/myflix:tfrecomm
    networks:
      - tfrecommnw
    command: ["/bin/sh", "-c", "cd /notebooks/TF-recomm && python svd_query.py"]


networks:
  tfrecommnw: