version: "3"

services:
  sql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_PORT: 3306
    networks:
      - sqlnetwork
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  flask-app:
    build: .
    depends_on:
      - sql-db
      - restheart
      - videoserver
      - tfrecomm
    ports:
      - "80:5000"
    networks:
      - sqlnetwork
      - flasknetwork
      - tfrecommnetwork

networks:
  sqlnetwork:
